//created on: 26 May 2022
package com.mycompany.rules

//list any import classes here.
import com.mycompany.app.Purchase

rule "purchase contains drink"
when
	$p : Purchase ( drinkIncluded )
then
	$p.setDiscount($p.getDiscount() + 0.05);
	System.out.println("Drink discount: " + $p.getDiscount());
	System.out.println();
	System.out.println("Drink discount: " + $p.getDiscount());
	
end


rule "purchase over 15 and less than 25 dollars"
when
	$p : Purchase ( total > 15, total <= 25 )
then
	$p.setDiscount(0.10);
	System.out.println("Level 1 discount: " + $p.getDiscount());
	modify ( $p ) { setDrinkIncluded(true)
					};
	System.out.println("Level 1 discount: " + $p.getDiscount());
					
end

rule "purchase over 25 dollars"
when
	$p : Purchase ( total > 25 )
then
	$p.setDiscount(0.15);
	System.out.println("Level 2 discount: " + $p.getDiscount());
end

rule "purchase contains combo" salience -1
when
	$p : Purchase ( drinkIncluded, tacoCount >= 2 )
then
	$p.setDiscount($p.getDiscount() + 0.05);
	System.out.println("Combo discount: " + $p.getDiscount());
end

