//created on: 26 May 2022
package com.mycompany.rules

//list any import classes here.
import com.mycompany.app.Message

global java.util.List list

rule "Good Bye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
end


rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println( message );
        modify ( m ) { setMessage( "Goodbyte cruel world. change place of second rule." ),
                       setStatus( Message.GOODBYE ) };
//    modify ( m ) { message = "Goodbye cruel world",
//                   status = Message.GOODBYE };
end

